### ISSUE TITLE
LCDモジュールをためす

### ISSUE THREAD

**Issue by PharaohKJ** [KanazawaIoT/seminar#10]

**Comment by PharaohKJ** [comment]
GEMをGitHubあたりにあげていただけるとありがたいです。

**Comment by izawa** [comment]
ほい。
https://gist.github.com/izawa/67fa163656a50640d552ccd54f2366a3

**Comment by PharaohKJ** [comment]
あざっす！っていうか加えてラズパイとの接続図もいりますね。
私も作らないといけないなあ。

**Comment by PharaohKJ** [comment]
2017-06-30に上記gistのURLにある内容で動作を確認できました。

1. ラズパイのI2Cを有効にする 
    1. `sudo raspi-config`
    1. メニューより `5 Interface Options`
    1. メニューより`P5 I2C`
2. はんだ付けする
3. 3.3V、GND、GPIO02(SDA1)、GPIO03(SDC1) を配線する
4. `sudo gem install i2c`
5. `wget https://gist.githubusercontent.com/izawa/67fa163656a50640d552ccd54f2366a3/raw/147896ea089ebc57682a36bb691d566bb64e730a/lcd-test.rb`
6. `ruby lcd-test.rb` で表示されればOK

<img width="1230" alt="2017-06-30 21 58 22" src="https://user-images.githubusercontent.com/1581985/27758537-4e85e684-5e51-11e7-8ab3-dbc40a32fbab.png">
<img width="1230" alt="2017-06-30 21 58 17" src="https://user-images.githubusercontent.com/1581985/27758536-4e82c850-5e51-11e7-9b16-0ffebdb0a41e.png">

**Comment by PharaohKJ** [comment]
他ページにまとめたのでここではクローズします。
