### ISSUE TITLE
6/7 議題

### ISSUE THREAD

**Issue by PharaohKJ** [KanazawaIoT/seminar#12]
- アンケート結果の参照

@izawa さん、すみませんが議事録ございました追記をしていただけないでしょうか？

**Comment by izawa** [comment]
Kanazawa IoT準備委員会
5/14議事録
参加者: kato, takeda, aiba, izawa(log)

* 宿題の進捗報告
  + kato
    ・本のとおりにやってみた。
    ・RPi3 でも Lircちゃんと動かすことが出来た。
      →/boot/config.txtをちゃんと作る
    ・秋月のパーツで作っているので、これをマルツさんのパーツで
      どう構成するのかを調べるのがToDoとしてある。
    ・デモ機材どうするのか
      →首振りサーキュレーターを加藤さんが持っている
      →みんな学習しないといけない。予め学習? →もうちょっと継続して構
        成を考える。

  + izawa
    ・動くのは確認できた。素直なデバイスでした(感謝)。
    ・ToDo: ruby gem から使えるようにしていきたい。

  + aibax
    ・MQTT mosquiteを立ててみた。
    ・相互通信のテストもした。
    ・awsのサービスとの比較調査をした。
    ・RPiのクライアントをどうするか、を継続して考えていきたい。

  + 次回: 6/5(月) 20:00-@マルツ


* 部材の値段を下げる施策を考えたい
  + n回に分散させたい
  + RPiの会をやるのもいいかもね。(Linuxの使い方みたいな内容)
    ・電源のon/offのしかたから。
    ・基本的なコマンド
    ・ディレクトリの構造
  + 座学のコースを設けるのもアリ。

**Comment by PharaohKJ** [comment]
:+1: ありがとうございます。

**Comment by izawa** [comment]
この他に、それぞれの要素技術を組み合わせて最終的にどういうものにするのかを考える必要もありますね

**Comment by PharaohKJ** [comment]
本日マルツさんのイベントに参加してマルツさんで買えるハードウェア互換テストしました。
無事、TVを操作できました。

赤外線受光モジュール
ＯＳＲＢ３８Ｃ９ＡＡ（2個100円） > マルツさん互換 RPM7138-R (1個158円)
https://www.marutsu.co.jp/contents/shop/marutsu/datasheet/rpm7138-j.pdf

発光LED
ＯＳＩ３ＣＡ５１１１Ａ　（１０個150円）> マルツさん互換 LSIR053（1個60円）
http://www.brightekeurope.com/productcart/pc/catalog/LSIR053(100mA).pdf

他部品
http://akizukidenshi.com/download/ds/toshiba/TD62783AFG_TD62783APG_ja_datasheet_110223.pdf

**Comment by PharaohKJ** [comment]
NT金沢 に Kanazawa IoT さんも出ませんか？とお誘いを受けました、

**Comment by izawa** [comment]
↑今日が申込締切ですが、どうしましょうかね。
当日対応出来る人がいるなら、気軽に申し込んで良いと思うのですが、何を出す？とか全く決まってないし今年は難しいかなー？

**Comment by PharaohKJ** [comment]
運営さんに月曜打ち合わせなんでそのあとお返事でもいいですか？とお伺いしたらOKもらいました。なので月曜決めましょう！
2017年5月31日(水) 14:31 いざわゆきみつ (Yukimitsu Izawa) <notifications@github.com>:

**Comment by izawa** [comment]
りょうかいです！

**Comment by PharaohKJ** [comment]
会も実施した。
