### ISSUE TITLE
次回用キット一式見積もり & 購入

### ISSUE THREAD

**Issue by PharaohKJ** [KanazawaIoT/seminar#13]
@takedafutoshi さん、マルツさんに以下の見積もりをお願いしてください。

- ジャンパワイヤセット メス>オス (GPIOとブレッドボード接続用)
- ジャンパワイヤセット オス>オス (ブレッドボード配線用)
- ジャンプワイヤセット メス>メス (GPIOとLCDキット)
- ブレッドボード
- LCDキット(マルツさんから @izawa さんに貸し出されたものと同じもの)
- 赤外線受光モジュール  RPM7138-R  1個
- 発光LED LSIR053（1個60円） 2個
- IC TD62783APG 1個

![img_2571](https://cloud.githubusercontent.com/assets/1581985/26817979/d94c6edc-4ad3-11e7-90bc-1de0a40e46e3.JPG)

**Comment by PharaohKJ** [comment]
Facebookのほうに連絡ありましたが、 2,540円だそうです。

まずは、4人分発注しちゃいますか。

とりあえず私としては今月末金曜日のメイカーズナイトに参戦して @izawa さんのGEM含めて
試しちゃおうかなと思ってるのですがどうでしょうか？

メイカーズナイトちょっとお高いけど・・・。

**Comment by izawa** [comment]
とりあえず4人分発注してしまってよいのではないでしょうか

**Comment by PharaohKJ** [comment]
それではそれでいきましょう！

**Comment by PharaohKJ** [comment]
Facebook上で @takedafutoshi さん経由で4つ発注しました。

**Comment by PharaohKJ** [comment]
@izawa さんのLCD表示部も含めて接続図を作成、実物の写真を取ること。
今月のメイカーズナイトでやりたいな。

**Comment by izawa** [comment]
電源の +(VCC) と -(GND) と SDAとSCL を RPi3の当該端子と接続するだけで動きます。
RSTは未接続でも大丈夫でした。ご参考まで

**Comment by PharaohKJ** [comment]
会も実施した。close
