### ISSUE TITLE
connpassで募集

### ISSUE THREAD

**Issue by PharaohKJ** [KanazawaIoT/seminar#6]
- [x] Kanazawa IoT チーム作成
- [x] 3/25 マルツ西インター店、13:00 - 18:00 で募集
  - 予算は2万円? (要部品一覧更新と打ち合わせ)

**Comment by PharaohKJ** [comment]
とりあえず上記は書いたが本募集は2月21日からとした。(2/20に打ち合わせのため)

チームは https://kziot.connpass.com
募集は https://kziot.connpass.com/event/49802/

で、ロゴとかバナー使ってみたけどダサいんで @takedafutoshi さんとなおす。

**Comment by PharaohKJ** [comment]
思いつきだけど、 Kanazawa IoT を略して KzIoT というロゴを作ったらいろいろ収まりがいいんじゃあないか？

**Comment by takedafutoshi** [comment]
それもありですね。
ただ、
Kanazawa IoT
として認知してもらいたいのか、
KzIoT
として認知してもらいたいのか、
によっても変わります。

**Comment by takedafutoshi** [comment]
個人的には
Kanazawa IoT
で、進めてもカッコよくは出来ると思います。

**Comment by takedafutoshi** [comment]
connpassで貼り付けるバナーと、ロゴと、
ついでにfbページに貼り付けるバナーと、ロゴと、
用意すればいいでしょうかね？
今のロゴをリニューアルするのではなくて、
今のロゴを活かしながら。

**Comment by PharaohKJ** [comment]
素材がないから適当にやっちゃったんで、おまかせします。（おもいのほかかっこよくならなかった）
とりあえず管理者にするので、connpassチームにジョインしてください。

**Comment by takedafutoshi** [comment]
ジョイン完了。

**Comment by PharaohKJ** [comment]
北陸CCCアカウントだけど大丈夫なの？

**Comment by takedafutoshi** [comment]
はい。僕のやつです。
そう言えば直してなかった、、

**Comment by PharaohKJ** [comment]
イベントとグループチームの管理者に指定しました。

画像さしかえとかできるようになったと思うんでよろしくです。
