### ISSUE TITLE
当日議題

### ISSUE THREAD

**Issue by PharaohKJ** [KanazawaIoT/seminar#7]
# 手順 & 資料について
- [x] 持ち帰ってもらったときの無線/有線LAN設定について言及する。
- [x] IPアドレスを調べる方法
- [x] Osakaにした。
- [x] tty.USB0のドットを抜いた。

# 決め事
- [x] 仕入れたものを売る方法。
- [x] 会計担当を決める。
- [x] 次回、内容に言及する。
- [x] アンケートをとる？

**Comment by izawa** [comment]
- [ ] TWE-LiteRとPCをつなぐためのUSBケーブルが、今回のKitに同梱されているか確認

**Comment by PharaohKJ** [comment]
`持ち帰ってもらったときの無線/有線LAN設定について言及する。`

フォローアップメールで連絡する。フォローアップキーノートを用意し connpass で共有 &  連絡する。

**Comment by PharaohKJ** [comment]
`IPアドレスを調べる方法`

1人1人まわってIPアドレスをディスプレイで確認し、メモしてもらう。
(自宅では変わることをつたえておくこと)

**Comment by PharaohKJ** [comment]
`仕入れたものを売る方法。`

今日は 1,500円キットを販売する。

内容 センサーとジャンパー

**Comment by PharaohKJ** [comment]
`会計担当を決める。`

@aibax さんにお願いする。

いまのところ、 
@izawa さんが2万円出資(そこから部品を仕入れた形にする)
@aibax さんがドメイン費出資
@PharaohKJ がロゴ費出資

とする

**Comment by PharaohKJ** [comment]
`次回、内容に言及する。`

- 同じ講習を3度やります。（毎月実施予定）
- Vol.2 はこのキットをなるべく使う内容にする。

**Comment by PharaohKJ** [comment]
`アンケートをとる？`

後日Googleフォームで行う。

**Comment by PharaohKJ** [comment]
(GoogleForm 仮) https://goo.gl/forms/DyNawqw8yIlpuVCm2

**Comment by PharaohKJ** [comment]
第一回を2度でいったん終了。なのでいったんこれはクローズ。
