### ISSUE TITLE
第２回実施に向けたToDo

### ISSUE THREAD

**Issue by izawa** [KanazawaIoT/seminar#9]
２回目実施に向けたToDoを整理してみました。
他にあれば追加してください。

- 仕入れ
    - [ ] BME280 秋月から通販 ( http://akizukidenshi.com/catalog/g/gK-09421/ )
    - [ ] ICジャンパケーブル マルツさんで8本入り(前回の残りがいくつかはあるはず。追加で必要。)
    - [ ] MicroSDカード 東芝8G class10 UHS-I マルツさんで購入が良い

- 当日用資材準備
    - [ ] 冷たいもの
    - [ ] 暖かいもの
    - [ ] MicroSDカード作成(Wifi情報改定したイメージの作成と焼き込み)

- 現地設営
    - [ ] 竹田さんのプロジェクタを持ち込む
    - [ ] 完成品をもっと準備しておく
    - [ ] イカ型タップを生やしておく

**Comment by PharaohKJ** [comment]
- BME280 は会計担当 @aibax さんが、5/8時点の申込状況を見て買う。(いくつ買うかはその時話ししましょう)
- ジャンパ > 買わなくてよい
- MicroSD > 買わなくて良い
- 冷たいもの > @PharaohKJ が当日用意
- 温かいもの > @PharaohKJ が当日用意
- MicroSDカードのwifiアップデートは @izawa さんが当日までに行う
- 完成品については 5/8時点の申込状況見て考える
- イカ型タップは会場にご用意いただく

**Comment by PharaohKJ** [comment]
5/9 12:45 の時点で3人。ベテランの方、少々できる方、不明、なのでまー完成品は1つあればOKかと。

**Comment by PharaohKJ** [comment]
@aibax さんが5個 BME280 仕入れた。会計記入もお願いします。

ワイヤは追加発注いらなさそう。

**Comment by PharaohKJ** [comment]
全部完了。無事終了。会計も終了。
